# Generated by Django 4.0.1 on 2022-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='idn',
            field=models.IntegerField(default=0),
        ),
    ]
